variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build
  - production

include:
  - local: .gitlab/ci/test.gitlab-ci.yml
  - local: .gitlab/ci/build.gitlab-ci.yml
  - local: .gitlab/ci/production.gitlab-ci.yml
