apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuY29tIjogewoJCQkiYXV0aCI6ICJhemh6T21WWFdYTktVRzF4Y1cxcGQyWjVNV3A0Ulc5aiIKCQl9Cgl9Cn0=
kind: Secret
metadata:
  labels:
    cattle.io/creator: norman
  name: gitlab-registry
type: kubernetes.io/dockerconfigjson
