deploy:
  stage: production
  image: dtzar/helm-kubectl
  before_script:
    - sed -i "s~<VERSION>~${CI_COMMIT_TAG}~g" .helm/Chart.yaml
  script:
    - helm upgrade pineapple-chart .helm --namespace "${KUBE_NAMESPACE}" --install
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
