lint:
  stage: test
  image: node:12-alpine
  before_script:
    - yarn install
  script:
    - yarn lint

unit:
  stage: test
  image: node:10-alpine
  before_script:
    - yarn install
  script:
    - yarn test:unit
